<Screen
  id="applePicker"
  _customShortcuts={[]}
  _hashParams={[]}
  _searchParams={[]}
  browserTitle=""
  title="applePicker"
  urlSlug=""
  uuid="b5270498-8148-4d03-96cc-4fc5c11d69cb"
>
  <Frame
    id="$main"
    enableFullBleed={false}
    isHiddenOnDesktop={false}
    isHiddenOnMobile={false}
    padding="8px 12px"
    type="main"
  />
</Screen>
